import { createStore } from 'vuex'
export default createStore({
    state: {
        currentDay: null,
        dailyMenu: [
            {
                id: 0,
                day: 'Pondelí',
                value01: '0,3l',
                value02: '1.',
                value03: '2.',
                value04: '3.',
                value05: '4.',
                price01: '25,-',
                price02: '100,-',
                price03: '110,-',
                price04: '115,-',
                price05: '110,-',
                meal01: 'Krémová česneková polévka',
                meal02: 'Zapečené brambory Trautenberk s kuřecím masem, nivou a pórkem',
                meal03: 'Kung – pao s jasmínovou rýží',
                meal04: 'Jídlo týdne – Vepřový steak gyros, tzatziki, pita, hranolky',
                meal05: 'Salát Caesar s kuřecím masem, krutony a parmazánem',
            },
            {
                id: 1,
                day: 'Úterý',
                value01: '0,3l',
                value02: '1.',
                value03: '2.',
                value04: '3.',
                value05: '4.',
                price01: '25,-',
                price02: '100,-',
                price03: '110,-',
                price04: '115,-',
                price05: '110,-',
                meal01: 'Krémová česneková polévka',
                meal02: 'Zapečené brambory Trautenberk s kuřecím masem, nivou a pórkem',
                meal03: 'Kung – pao s jasmínovou rýží',
                meal04: 'Jídlo týdne – Vepřový steak gyros, tzatziki, pita, hranolky',
                meal05: 'Salát Caesar s kuřecím masem, krutony a parmazánem',
            },
            {
                id: 2,
                day: 'Středa',
                value01: '0,3l',
                value02: '1.',
                value03: '2.',
                value04: '3.',
                value05: '4.',
                price01: '25,-',
                price02: '100,-',
                price03: '110,-',
                price04: '115,-',
                price05: '110,-',
                meal01: 'Krémová česneková polévka',
                meal02: 'Zapečené brambory Trautenberk s kuřecím masem, nivou a pórkem',
                meal03: 'Kung – pao s jasmínovou rýží',
                meal04: 'Jídlo týdne – Vepřový steak gyros, tzatziki, pita, hranolky',
                meal05: 'Salát Caesar s kuřecím masem, krutony a parmazánem',
            },
            {
                id: 3,
                day: 'Čtvrtek',
                value01: '0,3l',
                value02: '1.',
                value03: '2.',
                value04: '3.',
                value05: '4.',
                price01: '25,-',
                price02: '100,-',
                price03: '110,-',
                price04: '115,-',
                price05: '110,-',
                meal01: 'Krémová česneková polévka',
                meal02: 'Zapečené brambory Trautenberk s kuřecím masem, nivou a pórkem',
                meal03: 'Kung – pao s jasmínovou rýží',
                meal04: 'Jídlo týdne – Vepřový steak gyros, tzatziki, pita, hranolky',
                meal05: 'Salát Caesar s kuřecím masem, krutony a parmazánem',
            },
            {
                id: 4,
                day: 'Pátek',
                value01: '0,3l',
                value02: '1.',
                value03: '2.',
                value04: '3.',
                value05: '4.',
                price01: '25,-',
                price02: '100,-',
                price03: '110,-',
                price04: '115,-',
                price05: '110,-',
                meal01: 'Krémová česneková polévka',
                meal02: 'Zapečené brambory Trautenberk s kuřecím masem, nivou a pórkem',
                meal03: 'Kung – pao s jasmínovou rýží',
                meal04: 'Jídlo týdne – Vepřový steak gyros, tzatziki, pita, hranolky',
                meal05: 'Salát Caesar s kuřecím masem, krutony a parmazánem',
            }
        ]
    },
    getters: {
        getCurrentDay: state => {
            return new Date().getDay() < 5 ? state.dailyMenu.find(i => i.id == new Date().getDay()) : null
        }
    }
})