export { default as Box } from "@/components/Box.vue"
export { default as Footer } from "@/components/Footer.vue"
export { default as MenuItem } from "@/components/MenuItem.vue"
export { default as Navigation } from "@/components/Navigation.vue"
export { default as Section } from "@/components/Section.vue"
